version: '3.8'
services:
  web:
    build: .
    container_name: web
    ports:
      - 5000:5000
    command: gunicorn --bind 0.0.0.0:5000 app:app --preload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    command: celery --app app.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: docker_composer_redis